apiVersion: v1
data:
  config.yaml: |-
    configVersion: v1
    kubernetes:
    - name: pods-to-label
      apiVersion: v1
      kind: Pod
      executeHookOnEvent: ["Added", "Modified"]
      resynchronizationPeriod: "10m"
      allowFailure: true
      labelSelector:
        matchExpressions:
        - {key: auto-labeler.maxsum.io/labeled, operator: DoesNotExist}
        - {key: node-label, operator: Exists}
kind: ConfigMap
metadata:
  name: auto-labeler-config
