apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auto-labeler
  name: auto-labeler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auto-labeler
  template:
    metadata:
      labels:
        app: auto-labeler
    spec:
      serviceAccountName: monitor-pods-acc
      containers:
      - image: ghcr.io/max-sum/auto-labeler:latest
        imagePullPolicy: Always
        name: auto-labeler
        env:
        - name: COPY_LABELS
          value: "topology.kubernetes.io/region,topology.kubernetes.io/zone,geo.maxsum.io/city,geo.maxsum.io/country,geo.maxsum.io/subcontinent,geo.maxsum.io/continent"
        - name: KUBECTL_TIMEOUT_SECONDS
          value: "10"
        volumeMounts:
        - mountPath: /etc/auto-labeler/
          name: operator-config
      volumes:
      - configMap:
          name: auto-labeler-config
        name: operator-config
